### PR TITLE
add secret override 

### PR DESCRIPTION
**Pull request by phac008**
preventing secrets in source code
should solve #33

### CODE REVIEW

**Comment by phac008** [comment]
@davideserio 👋 i would like to contribute

**Comment by davideserio** [comment]
Hi,

Apologies for the delay in getting back to you.
I should be back to work in the next few hours and will take care of your request.

**Comment by davideserio** [comment]
Hi,

After fixing a lint error, I encountered an issue during the automatic push because the PR branch had the same name as "main". Unfortunately, this caused the PR to close, and I couldn't reopen it. Could you please reopen the PR so I can proceed with the merge?

Thanks!

**Comment by davideserio** [comment]
4

**Comment by davideserio** [comment]
Hi,

After fixing a lint error, I encountered an issue during the automatic push because the PR branch had the same name as "main". Unfortunately, this caused the PR to close, and I couldn't reopen it. Could you please reopen the PR so I can proceed with the merge?

**Comment by davideserio** [comment]
Solved in #40

**Pull request closed without merging**
